title: Dimitris Athanasakoglou
description: personal website
author: Dimitris Athanasakoglou
logo: /dathanasakoglou.github.io/static/img/avatar.svg
github: https://github.com/dathanasakoglou
about: Junior Data Scientist

baseurl: "https://dathanasakoglou.github.io"
url: "https://dathanasakoglou.github.io"

allowsearch: true

disqus_shortname:
google_analytics: UA-80721578-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
